# Generated by Django 4.0.4 on 2022-05-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maibeauty', '0002_remove_lips_description_remove_lips_photo_url_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brows',
            new_name='Brow',
        ),
        migrations.RenameModel(
            old_name='Eyes',
            new_name='Eye',
        ),
        migrations.RenameModel(
            old_name='Lips',
            new_name='Lip',
        ),
    ]
